name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install redis-cli
        run: sudo apt-get update && sudo apt-get install -y redis-tools
      - name: Wait for DB & Redis
        run: |
          until pg_isready -h localhost -U testuser; do sleep 2; done
          until redis-cli -h localhost ping; do sleep 2; done
      - name: Run tests
        run: pytest
      - name: Build Docker image
        run: docker build -t myapp:latest .
